#!/bin/bash
WATERNUM="$(echo -e ${WATER} | tr water 01234)" && STIRNUM="$(echo -e ${STIR} | tr stir. 01234)" && SUMWATERSTIR=$((5#$WATERNUM+5#$STIRNUM)) && BASEEIGHT="$(echo "obase=8; $SUMWATERSTIR" | bc)" && BEHLNORT="$(echo -e $BASEEIGHT | tr 01234567 behlnort)" && echo $BEHLNORT
